package com.app.common.modules.queuemanager.dtos;

import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;

import com.app.common.modules.queuemanager.enums.ItemStatus;

/**
 * Represents an export queue root row and owns the file leaf rows beneath it.
 * <p>
 * In the export queue, the root row id is the normalized destination directory
 * path. Leaf rows use the full destination export path generated by the export
 * worker.
 */
public class ExportDirectoryQueueItem {
    private final Path exportDir;
    private ItemStatus status;
    private final List<FileQueueItem> files;
    private int total;
    private int passed;
    private int failed;

    /**
     * Creates an export destination root row.
     *
     * @param exportDir root row id and display value for the export destination
     */
    public ExportDirectoryQueueItem(Path exportDir) {
        this.exportDir = exportDir;
        this.status = ItemStatus.QUEUED;
        this.files = Collections.synchronizedList(new ArrayList<>());
    }

    /**
     * Returns the export root row id.
     *
     * @return normalized export directory path
     */
    public Path getExportDir() {
        return exportDir;
    }

    /**
     * Returns the display name for the export root row.
     *
     * @return export directory path shown in the queue UI
     */
    public String getDisplayName() {
        return exportDir.toString();
    }

    /**
     * Returns the aggregate status shown on the export directory root row.
     *
     * @return current directory/root row status
     */
    public ItemStatus getStatus() {
        return status;
    }

    /**
     * Sets the aggregate status shown on the export directory root row.
     *
     * @param status current directory/root row status
     */
    public void setStatus(ItemStatus status) {
        this.status = status;
    }

    /**
     * Returns the export file leaf rows owned by this directory root row.
     *
     * @return mutable list of file rows whose root row id is this directory path
     */
    public List<FileQueueItem> getFiles() {
        return files;
    }

    /**
     * Adds a file and keeps queued export rows ordered by size so the UI mirrors
     * the worker's processing order whenever files are appended to a directory.
     *
     * @param file file row whose row id is the full destination export path
     */
    public void addFile(FileQueueItem file) {
        files.add(file);
        sortFiles();
    }

    /**
     * Removes a file leaf row from this export directory root row.
     *
     * @param file file row whose row id is the full destination export path
     */
    public void removeFile(FileQueueItem file) {
        files.remove(file);
    }

    /**
     * Orders leaf rows by sort size while keeping unknown sizes at the end.
     */
    public void sortFiles() {
        synchronized (files) {
            files.sort(Comparator.comparingLong(file -> file.getSortSize() != null
                    ? file.getSortSize()
                    : Long.MAX_VALUE));
        }
    }

    /**
     * Returns the total number of files reported for this export root row.
     *
     * @return aggregate total count
     */
    public int getTotal() {
        return total;
    }

    /**
     * Sets the total number of files reported for this export root row.
     *
     * @param total aggregate total count
     */
    public void setTotal(int total) {
        this.total = total;
    }

    /**
     * Returns the number of successful files for this export root row.
     *
     * @return aggregate passed count
     */
    public int getPassed() {
        return passed;
    }

    /**
     * Sets the number of successful files for this export root row.
     *
     * @param passed aggregate passed count
     */
    public void setPassed(int passed) {
        this.passed = passed;
    }

    /**
     * Returns the number of failed files for this export root row.
     *
     * @return aggregate failed count
     */
    public int getFailed() {
        return failed;
    }

    /**
     * Sets the number of failed files for this export root row.
     *
     * @param failed aggregate failed count
     */
    public void setFailed(int failed) {
        this.failed = failed;
    }
}
